const actionTypes = Object.freeze({
    FETCH_USER_LOGIN_SUCCESS: 'FETCH_USER_LOGIN_SUCCESS',
    FETCH_USER_LOGOUT_SUCCESS: 'FETCH_USER_LOGOUT_SUCCESS',
    FETCH_DETAIL_PRODUCT_SUCCESS: 'FETCH_DETAIL_PRODUCT_SUCCESS',
    FETCH_ALL_PRODUCT_SUCCESS: 'FETCH_ALL_PRODUCT_SUCCESS',
    REMOVE_SELECTED_PRODUCT: 'REMOVE_SELECTED_PRODUCT',
    FETCH_ALL_PRODUCT_IN_WISHLIST: 'FETCH_ALL_PRODUCT_IN_WISHLIST',
    FETCH_ALL_PRODUCT_IN_CART: 'FETCH_ALL_PRODUCT_IN_CART',
    REMOVE_PRODUCT_IN_CART: 'REMOVE_PRODUCT_IN_CART',
    FETCH_CATEGORIES: 'FETCH_CATEGORIES',
    FETCH_BOOKING: 'FETCH_BOOKING',
    FORGOT_PASSWORD: "FORGOT_PASSWORD",
    RESET_PASSWORD: "RESET_PASSWORD",

})

export default actionTypes